### ISSUE TITLE
ESP32

### ISSUE THREAD

**Issue by AndyIP70** [vvip-68/GyverLampWiFi#10]
Добрый вечер!
У меня просьба, создайте пожалуйста порт данной прошивки для платформы ESP32 (ESP32 Dev Module).
Я сам пробовал, кроме кучи ошибок ничего не добился :(

**Comment by vvip-68** [comment]
Ну так спрашивал бы где на форуме, в обсуждениях что за ошибки, как их устранять.
Я про ESP32 ничего не знаю и как его вообще в Arduino IDE прикручивать тоже. И в наличии у меня его нет. Портируешь - пиши. 
А почему тебе именно ЭТОТ вариант лампы нужен?
Вон у Гуннера лампу уже давно под ESP32 портировали. Там и возможностей много больше.
https://community.alexgyver.ru/threads/wifi-lampa-budilnik-obsuzhdenie-proekta.1411/page-52#post-14055

**Comment by AndyIP70** [comment]
Мне нравится вариант с часами и музыкой :) Да сама реализация кажется более удобной.
Вообщем мне все удалось портировать, за исключением одного момента.
В файле clock.ino есть такая строка:
if (!timeServerIP.isSet()) timeServerIP.fromString(F("192.36.143.130"));
при использовании ESP32 подключается другая библиотека методов TCP/IP UDP
и данного метода (.isSet) там просто нет.
Я заменил эту строку следующим кодом:
String ip = "";
  if (!timeServerIP.fromString(ip)) timeServerIP.fromString(F("192.36.143.130"));
вроде прокатило, прошивка компилится без проблем.
Но, я не уверен что данный код работает правильно... :)
Ну и собственно если код работает не правильно - хотел бы получить совет как обойти это препятствие.

**Comment by vvip-68** [comment]
Ну так то вроде все верно - if (!timeServerIP.fromString(ip)) по документации возвращает false, если не удалось из строки получить валидный IP адрес. Должно работать.

**Comment by AndyIP70** [comment]
Спасибо!
