### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by udavst** [vvip-68/GyverLampWiFi#15]
Почему-то приложение не запускается, белый экран и вылетает. Mate20, Android 9, права даны.

**Comment by vvip-68** [comment]
Попробуйте переустановить приложение. Возможно у вас недостаточно свободной памяти- освободите ее. Если есть аккаунт в Thunkable Classic - загрузите исходник приложения (aia-файл) в конструктор и соберите приложение оттуда, затем загрузите его в телефон.

**Comment by udavst** [comment]
Переустанавливал, памяти полно, ~300 других приложений горя не знают. Зарегился в Thunkable, загрузил проект, нажал сохранить apk - не устанавливается, ошибка пакета. Более глубоко с Thunkable, видимо, я разберусь не скоро (
Оригинальная GyverLamp и GyverLamp от AK47 работают.

**Comment by vvip-68** [comment]
Ну если вы таки в Thunkable - у вас есть аккаунт в Classic. Это отлично.
apk надо собирать в 26-ой версии API
В 28-ой не соберется. Thunkable не переваривает таких больших программ в 28 API

**Comment by udavst** [comment]
Видимо не судьба( я на https://x.thunkable.com загружаю GyverLampWiFi.aia, показывает, что загружен, но ничего на экране не меняется, тест на телефоне показывает тот же белый экран, меню выбора апи я вообще не нашёл, есть только скачать апк, и тестировать  на телефоне, странный сайт, никаких инструментов.
Запускал Вашу программу на эмуляторе самсунга S7 - работает.

**Comment by vvip-68** [comment]
Может у вас с компом что-то не так? Вот только сегодня утром приложение правил - разметку, чтобы на узких телефонах кнопка не "уплывала"...

**Comment by udavst** [comment]
Я понял, я файл в проект импортирую, а надо как готовый проект, но нет на сайте этих кнопок, пробовал уже в разных браузерах (
http://bel.ddns.info/index.php?twg_album=%D0%A2%D0%B5%D1%81%D1%82&twg_show=Screenshot_2019-12-17+Thunkable.png&twg_zoom=FALSE

**Comment by vvip-68** [comment]
https://drive.google.com/file/d/1tAyQd0gGyJiIeBybreIidRstMf7WMr0M/view?usp=sharing

**Comment by udavst** [comment]
Ну ладно, обойдусь значит. Меня на сайт на скриншоте не пускает, перекидывает на новый сайт https://x.thunkable.com - а там нет импорта.

**Comment by vvip-68** [comment]
Ну да, Classic закрыт для подключения новых пользователей. Проект из Classic в Иксы загрузить невозможно - там совсем другая инфраструктура. В иксах можно только заново с нуля проект создавать. Но он очень кастрированный, многих нужных расширений в иксах просто нет. Не видел еще ни одного реального проекта созданного в иксах - так, баловство, тесты, упражнения простейшие.
