### ISSUE TITLE
Приложение для андроида

### ISSUE THREAD

**Issue by Militar49** [vvip-68/GyverLampWiFi#16]
На 9 андроид приложение не работает... Вылетает при запуске, помогите решить проблемму

**Comment by vvip-68** [comment]
На андроид 9 приложение работает. У самого телефон с 9-ым андроидом.
То что не работает конкретно на вашем телефоне... Проблема скорее всего именно в вашем телефоне.
Не знаю. Ничем помочь не могу. Приложение собрано в конструкторе Thunkable Classic - вот как он собирает, такое и приложение получается. И ничего с этим поделать нельзя. Это не управляется.

**Comment by Militar49** [comment]
Проверял на 2 телефонах хонор 20 и хонор 10 вылетает при запуске, на сони
эхспирия с 7 андроид ом работает,


пт, 20 дек. 2019 г., 15:14 vvip-68 <notifications@github.com>:

**Comment by ermiyaev** [comment]
Думаю, что в эти дебри с тонкостями Kirin никто не полезет. Если только писать в поддержку Thunkable.

Есть вариант поставить модифицированную прошивку от lakec с управлением через веб морду. Из хрома на телефоне создать ярлык на рабочий стол на адрес лампы и пользовать вместо приложения. Кроме рассвета....
Для настройки рассвета можно на комп поставить NOX (эмулятор андроид), а туда поставить приложение попробовать, один раз настроить и всё.
Да, я знаю, что это не то, что ты спрашивал, но это какой-то выход из ситуации.

**Comment by Militar49** [comment]
Спосибо

пт, 20 дек. 2019 г., 15:48 ermiyaev <notifications@github.com>:
