### ISSUE TITLE
Проблема с включением будильника из программы на андроид.

### ISSUE THREAD

**Issue by AnatolyDem** [vvip-68/GyverLampWiFi#18]
Здравствуйте. Собрал я лампу по вашему проекту, все работает кроме будильника. Если я ставлю будильник из программы WiFiLamp на смартфоне (андроид 8.1.0) то не могу включить, если разница между реальным временем и заданным больше 10 минут.. Если разница-  например: у меня время показывает 4-05...я ставлю будильник на 4-15 или меньше...то включается (на смарте появляется кнопка отключение) будильник работает и все срабатывает. если больше 10 минут  разница, то включения нет и при нажатии в программе, в закладке "Настройки будильника", кнопки "Установить" происходит моргание лампы и ничего не меняется. Я уж и не знаю где рыть. Даже подключается программа GyverMatrix, многие режимы из нее работают, но с будильником проблема

**Comment by vvip-68** [comment]
Проверил неоднократно, попросил проверить знакомых, которые собрали лампу. Никаких проблем с установкой будильника не выявлено. У всех все устанавливается и срабатывает в установленное время.
Если у вас продолжительность рассвета установлено 10 минут, то установка времени меньше чем за 10 минут до приводит сразу же к срабатыванию будильника. ТО есть - все работает правильно.
Моргание ламы - симптом странный. Не вижу причин что бы могло вызвать моргание.
Программы GyverMatrix и GyverLamp имеют похожий, но все же разный протокол обмена с устройством. Если пытаться управлять программой для несоответствующего устройства - работать корректно не будет.

**Comment by AnatolyDem** [comment]
сегодня еще поэкспериментировал, почему-то все завязано со временем рассвета, как я понял можно выставить от 1 до 59 минут...вот в пределах этого времени я могу выставить будильник от реального времени. Например: если сейчас время 14-00...я ставлю рассвет 59 минут( то есть это время рассвета до сработки будильника) то могу выставить будильник не более 14-59, до этого времени будильник выставляется и срабатывает....если ставлю 15-00, то не могу включить...при начатии кнопки "Установить" лампа моргает и все, остается включенным обычный режим ...что я не так делаю...есть еще настройки которые надо изменить или выставить в прошивке...потому что первая проблема была в размерах матрицы..в прошивке была выставлена 17 на 9...а у меня 16 на 16(стандартная панель с китая) и я не мог понять почему нормально не работает

**Comment by vvip-68** [comment]
А что вы ожидаете после нажатия кнопки "Установить"?

**Comment by AnatolyDem** [comment]
хоть какого-то сообщения, понимания, индикатора, что будильник выставился и включился. Я конечно сейчас еще раз поставлю на часа два и посмотрю сработку будильника... и время рассвета выставлю минут 10. Может я чего не понял в логике работы и меня смущает что нет индикации что будильник включился...сейчас настрою и подожду

**Comment by vvip-68** [comment]
Нет никакой индикации (на лампе). Если будильник установился - это показывается в программе, что время установлено и движок вкл/выкл в положении вкл. Время рассвета - за сколько до установленного времени будильники она включится если была выключена или переключится в режим рассвета, если был какой другой эффект. В течение указанных 10 минут будет плавно нарастать яркость. Если подключены звуки - будет воспроизводиться мелодия рассвета с плавным нарастанием громкости. Во время установленное для будильника лампа загорится ярким белым светом и включится звук будильника. Это будет происходить установленное время (обычно 1 минуту) После этого будильник выключится. Всё. Никакой другой логики не предусмотрено.

**Comment by AnatolyDem** [comment]
вот сейчас попробовал опять, у меня время 15-20, я выставил рассвет 10 минут и время сработки будильника на 16-30..нажимаю на "Установить" и лампа кратко моргает и продолжает работать...а вроде должна перейти в режим пониженной яркости и режим будильника...снял видео, могу скинуть что я делаю..но как это сделать?

**Comment by vvip-68** [comment]
Не должна.

**Comment by AnatolyDem** [comment]
не должна "..должна перейти в режим пониженной яркости и режим будильника" Почему?...я же вроде хочу включить будильник и основной режим уже не нужен...то есть я включил будильник и теперь все работает и когда лампа не нужна отключаю ее кнопкой или со смарта и будильник работает...должен сработать...подожду

**Comment by AnatolyDem** [comment]
не понятно, включился ли режим будильника..нет никакой индикации

**Comment by vvip-68** [comment]
Индикация только в программе. Настраиваете нужные дни и время. Если настройки сохранены - они так и останутся как вы установили. Если что-то пошло не так - отобразится актуальное состояние настроек будильника. Установка времени срабатывания будильника вовсе не означает что оно должно перейти в режим пониженной яркости и все такое. 
Я поставил время (на завтра / на послезавтра / на 5 дней вперед, а лампа продолжает работать - зачем ей переходить в режим пониженной яркости?
Если вам привычнее другая логика - исходники открыты, переделайте как нужно вам.

**Comment by AnatolyDem** [comment]
спасибо, все нормально. я к сожалению не смогу настроить логику работы сам...пока учусь, помаленьку разбираюсь. Сейчас выставил время, жду сработки. Спасибо за ответы.

**Comment by AnatolyDem** [comment]
все сработало нормально :) БЛАГОДАРЮ.  Буду пробовать добавить мелодии будильника. Есть какие нибудь ограничения для этого? или просто достаточно кинуть в папки файлы? разбираюсь пока

**Comment by vvip-68** [comment]
Да не вижу пока ограничений навскидку. Кинуть в папку мало, нужно в скрипте список названий дополнить.

**Comment by AnatolyDem** [comment]
да я так и понял, сейчас ищу где в скрипте прописан список...вроде видел, но пока не нашел :)

**Comment by AnatolyDem** [comment]
извините :( не могу найти где прописаны звуковые файлы

**Comment by vvip-68** [comment]
В основном файле проекта
#define ALARM_SOUND_LIST F("One Step Over,In the Death Car")            // Список звука для комбобокса "Звук будильника" в приложении на смартфоне
#define DAWN_SOUND_LIST F("Птицы,Гроза,Прибой,Дождь,Ручей,Мантра")      // Список звука для комбобокса "Звук рассвета" в приложении на смартфоне

**Comment by AnatolyDem** [comment]
фуф...это же проект GyverLampWiFi , а не GyverMatrixOS.......в проекте GyverLampWiFi нет таких строк ...они есть в GyverMatrixOS

**Comment by AnatolyDem** [comment]
в проекте GyverLampWiFi есть часы на индикаторе TM1637 и есть звуковой модуль, а в проекте GyverMatrixOS физически часов нет

**Comment by vvip-68** [comment]
Эти настройки есть и там и там.
В проекте GyverMatrixOS физических часов нет.
И что?

**Comment by AnatolyDem** [comment]
да я просто собирал GyverLamp из за часов с индикатором....а в проекте GyverLamp я не нашел таких или подобных строк...не нашел перечислений аудио файлов....а разве в проект GyverMatrixOS можно подключить индикатор, без правки самого проекта

**Comment by vvip-68** [comment]
Естественно нельзя. Это разные проекты с разным кодом. Но код процентов на 50% совпадает. В части будильников / звуков - на все 90% совпадает. В том числе и со списками названий звуков. В этом отношении всё одинаково.

**Comment by vvip-68** [comment]
Не нашел - сочувствую. Плохо искал.

**Comment by AnatolyDem** [comment]
наверно плохо, но уже по 4 разу весь построчно гляжу :(

**Comment by vvip-68** [comment]
В IDE есть кнопка - F3
Можно ввести строку для поиска и найти.
Ищи "ALARM_SOUND_LIST" остальное рядом
А вообще - это строки 222 и 223

**Comment by AnatolyDem** [comment]
нету на этих строках таких записей....223 вообще пустая и рядом нет, искал, может сместились....я не правил, просто скачал от сюда, исправил размеры матрицы на 16/16  и все ...:(

**Comment by AnatolyDem** [comment]
![image](https://user-images.githubusercontent.com/59547105/71898973-bb307c00-316b-11ea-837c-19b4032d5d3f.png)

**Comment by AnatolyDem** [comment]
скачивал прям здесь 
![image](https://user-images.githubusercontent.com/59547105/71899036-ee730b00-316b-11ea-8ecf-e489c0b1b485.png)

**Comment by AnatolyDem** [comment]
и строку ALARM_SOUND_LIST не находит.....я сразу начал так искать...потом сам, руками, построчно

**Comment by vvip-68** [comment]
Ну тогда ничем помочь не смогу, видимо...
Вот что прямо там при открытии файла на GitHub
![image](https://user-images.githubusercontent.com/39353139/71899674-c9dc5a80-318e-11ea-9e16-cee569c7878f.png)

**Comment by AnatolyDem** [comment]
странно. как так то....прям на сайте открывается по другому...это что, скачивается другой файл что ли?

**Comment by vvip-68** [comment]
Попробуй скачать еще раз

**Comment by AnatolyDem** [comment]
этот файл открытый в Arduino отсутствует кусок проекта....файл качал уже (4) четыре раза в разные папки и из каждую открывал, смотрел...сейчас еще раз скачаю

**Comment by AnatolyDem** [comment]
все, в этом файле есть такие строки :)...вы исправили? обновили файл? Благодарю.

**Comment by AnatolyDem** [comment]
я уже хотел этот недостающий кусок  воткнуть в ту версию с которой я мучился ;)...спасибо что исправили

**Comment by vvip-68** [comment]
Ты же видишь - что последнее обновление  - 13 дней назад. И оно касалось не этого куска кода. Этот - со списком файлов - мне кажется с месяц назад был изменен... Ну или по крайней мере в начале 20-х чисел декабря...

**Comment by vvip-68** [comment]
И имей в виду, что программу на телефоне требуется тоже обновить в соответствии с изменениями в прошивке.

**Comment by AnatolyDem** [comment]
у меня эти файлы были скачены в разные папки, изучал мучился,  2 декабря 2019, 2 января и 6 января 2020...у всех отсутствует этот кусок

**Comment by vvip-68** [comment]
Да, посмотрел по коду - он был добавлен 7 декабря. И соответственно 2 и 6 января просто обязан быть на месте.

**Comment by AnatolyDem** [comment]
наверно...надо поудалять лишнее скаченное, чтоб не мешало...да, от 6 января есть изменения

**Comment by AnatolyDem** [comment]
Спасибо.

**Comment by AnatolyDem** [comment]
все отлично добавилось, прописалось. Музыка играет, лампа радует. Благодарю за помощь.
