### ISSUE TITLE
MP3 плеер

### ISSUE THREAD

**Issue by dipcore** [vvip-68/GyverLampWiFi#2]
Можно ли добавить функционал mp3 плеера с флеш карты. Хорошая бы лампа с музыкой в детскую получилась бы.

**Comment by AndyIP70** [comment]
Доброго времени суток vvip-68!
Подскажите пожалуйста, данный проект (GyverLampWiFi
) основан на версии 1.4 от AlexGyver?
Если нет - не могли бы вы синхронизировать этот проект с версией 1.4

**Comment by vvip-68** [comment]
Хм.. Я галочку себе поставлю, но вопрос сроков реализации и вообще буду ли я это делать - даже не знаю. Это ж кроме проигрывания нужно как-то интерфейсно (в приложении например) реализовывать управление - что играть, как играть, всякий доп. функционал. Какие-то кнопки... Но, в принципе, идея интересная, достойна обдумывания...

**Comment by BaLD-91** [comment]
Поддерживаю идею! Раз уже есть плеер и динамик, было бы классно релаксировать, глядя на лампу, под треск огня, пение птичек, шум леса и т.д.

**Comment by vvip-68** [comment]
Ну так то это и сейчас возможно - именно перечисленные звуки есть на карточке, включить их можно на вкладке "Будильник" в приложении - там комбобокс выбора звука рассвета и кнопка "Пуск" чтобы начать воспроизведение.  Файлы достаточно длинные, на несколько минут, к тому же, кажется, воспроизведение зациклено.
