### ISSUE TITLE
Окно поиска локальной сети не открывается после подключения к точке доступа

### ISSUE THREAD

**Issue by ACKET2009** [vvip-68/GyverLampWiFi#20]
Здравствуйте! Не могу получить окно поиска и подключения к локальной сети. Подключился к точке доступа и всё на этом... зайти на 4.1 не даёт... как настраивать, не понятно.. приложение на хуавей мейт 20 не запустилось, хотя от Алекса и Ганнера приложения работают. Хотел именно Ваш вариант запустить. с сенсорной кнопкой нашёл где настройки поменять, с неё управляется, а с сетью засада какая-то... Указал напрямую точку доступа  и пароль, потом поменял явно указанный 192.168.0.116 на 1.116 (в своей сети, тогда прицепилась) Но с телефона не получилось так чтобы настроить и сохранить в епром. прошивал с перезаписью всего...

**Comment by Zluka-MV** [comment]
Поддерживаю, у меня проблема с приложением на Huawei Nova 2i. Лампа работает только в деморежиме, к роутеру подключилась, время показывает. Приложение не запускается, просто белый экран и потом сбрасывается. На виртуальном андроиде приложение запустилось. но не соеденилось.

**Comment by vvip-68** [comment]
Данный вариант не использует WiFiManager (всё делается прямым указанием адреса подключения) - следовательно никакого окна поиска локальной сети и быть не может. Это вы с каким-то другим проектом попутали. С тем, что вместо приложения белый экран - не подскажу, не сталкивался. Возможно ваша версия андроида не поддерживается приложением или несовместимость с какими-то другими установленными приложениями
