### ISSUE TITLE
Не создает Wi-fi сеть

### ISSUE THREAD

**Issue by Neo20201** [vvip-68/GyverLampWiFi#21]
Здравствуйте. После прошивки лампа запускается,но в поиске Wi-fi только есть AppLamp и все, AutoConnectAP отсутствует . В строке 366 указал имя NETWORK_SSID "AutoConnectAP" в строке 367 указал пароль   NETWORK_PASS "12345678"   В eeprom менял флаг как написано в разделе FAQ. Так же в 536 строке стоит WiFi.mode(WIFI_STA),Но лампа работает только в режиме точки доступа, а сеть для подключения ее к роутеру не создает  ПРОШУ ПОМОГИТЕ ПОЖАЙЛУСТА РЕШИТЬ ВОПРОС!!!!!

**Comment by vvip-68** [comment]
Это всё, что вы описали - из какого-то другого проекта. Данный проект ничего такого не поддерживает, и название точки доступа другое, и пароль для подключения другой. Как подключиться и что указывать - всё на главной страничке проекта написано.

**Comment by Neo20201** [comment]
Все же я сумел разобраться. После подключения к точке доступа все настройки есть в самой программе для мобильного устройства.
