### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by ooomakon** [vvip-68/GyverLampWiFi#23]
Здравствуйте,выдаёт ошибку
![Снимок экрана (7)](https://user-images.githubusercontent.com/59833449/102314587-84c2ca00-3f94-11eb-8ec6-0bba4f447d09.png)

**Comment by vvip-68** [comment]
Полагаю, что у вас идет сборка под ESP32 и стоит старая версия ядра?
Либо обновите версию ядра до актуальной, либо определите max() дефайном

#if defined(ESP32)
#ifndef min
  #define min(a,b) (((a) < (b)) ? (a) : (b))
#endif
#ifndef max
  #define max(a,b) (((a) > (b)) ? (a) : (b))
#endif
#endif

**Comment by vvip-68** [comment]
Либо это порожденная (вторичная) ошибка, и настоящая ошибка-первопричины - выше по логу компиляции

**Comment by ooomakon** [comment]
еслиб я понимал ,то было бы хорошо

**Comment by vvip-68** [comment]
Ну, ок. А от меня то вы что хотите? Я чем могу помочь? 
Зайти удаленно на ваш комп, все проверить, настроить, устранить ошибку и собрать всё?

**Comment by vvip-68** [comment]
Судя по скриншоту  и проекту (я повспоминал) - это не связано с ESP32 и версией - это ошибка порожденная и нужно в логе компиляции смотреть первопричину

**Comment by ooomakon** [comment]
Всё удалил и на чистое поставил Ардуино,прошилось и заработало!Спасибо!
