### ISSUE TITLE
ver 1.4 or not?

### ISSUE THREAD

**Issue by AndyIP70** [vvip-68/GyverLampWiFi#3]
Доброго времени суток vvip-68!
Подскажите пожалуйста, данный проект (GyverLampWiFi
) основан на версии 1.4 от AlexGyver?
Если нет - не могли бы вы синхронизировать этот проект с версией 1.4

**Comment by vvip-68** [comment]
Нет, не на версии 1.4 от Гайвера. Ничего общего. Функционал - тот же самый и даже больше (часы на TM1637 например, рассвет) внутри код другой. Что значит синхронизировать?

**Comment by AndyIP70** [comment]
Прошу прощения. Я имел в виду синхронизировать с версией 1.4 если ваш код основан на коде от AlexGyver версии 1.3 к примеру.
На так как это ваш собственный код - просьба не имеет смысла :)
И кстати спасибо за последние фиксы кода. Стабильность - это всегда хорошо!
И еще вопрос - планируется ли портирование для платы esp32?
ESP8266 - ведет себя очень не стабильно, часто перезагружается не смотря на все усилия:
стабилизировал питание +5v, переводил схему на +3v - один фиг. Ребуты самы разные. Может проработать 10 минут, а может и 2 часа. :(

**Comment by k0cm0c** [comment]
> ESP8266 - ведет себя очень не стабильно, часто перезагружается не смотря на все усилия:
> стабилизировал питание +5v, переводил схему на +3v - один фиг. Ребуты самы разные. Может проработать 10 минут, а может и 2 часа. :(

у меня на руках 2 штуки  esp8266mod ai-thinker он же ESP-12F один работает стабильно. у другого глюки через раз. Ни с питанием, ни с прошивкой, какой либо закономерности нет, возможно стоит поменять на другой

**Comment by vvip-68** [comment]
Я ставил эксперименты. Заливал разные прошивки и запускал на сутки (или до первого вылета) с монитором порта. Прошивки эти - GyverMatrixBT, GyverLamp 1.4, вот эта лампа GyverLampWiFi и GyverMatrixWiFi 1.13. Вылетают ВСЕ. Могут проработать почти сутки без сбоев, могут 3 раза за час перегрузиться. Зависит, видимо, от фазы луны. Даже убирал все из прошивки и в loop() оставлял только вызов эффекта "Матрица". Вылетает и в таком варианте.
Однако, взял пустую прошивку, добавил туда UDP и чтение (прослушивание) и один из примеров от FastLED. Такой вариант проработал трое суток без вылетов. Так что - ХЗ почему вылетает. Или нестабильность ядра ESPшки или проблемы в библиотеке FastLED.
У FastLED вышло обновление до 3.2.2 - поставил его. Прошло 12 часов - пока не вылетало. Подождем еще пару суток. Или они поправили что-нибудь у себя, или попробуем переписать код для использования AdaFruit вместо FastLED

**Comment by vvip-68** [comment]
>И еще вопрос - планируется ли портирование для платы esp32?

Не планировал. У меня и платы то такой нет. Насколько я знаю она [значительно] дороже ESP8266 и значительно мощнее. Применение ее тут - что из пушки по воробьям.
А что, напрямую без переделок, если прошивку в нее залить - не собирается?

**Comment by k0cm0c** [comment]
> У FastLED вышло обновление до 3.2.2 - поставил его.

Тоже обновил, 3.3.2 поставлю на прогон )

**Comment by vvip-68** [comment]
Вылетает все равно. Придется, видимо, на AdaFruit переписывать

**Comment by AndyIP70** [comment]
Нез наю как именно, но последний релиз очень стабилен :)
