### ISSUE TITLE
продолжает работать в режиме AP_STA после получения статического адреса

### ISSUE THREAD

**Issue by k0cm0c** [vvip-68/GyverLampWiFi#4]
https://github.com/vvip-68/GyverLampWiFi/blob/7b39d409c11533ff9d039b51cb9a21bcccb5e53c/firmware/GyverLampWiFi_v1.00/GyverLampWiFi_v1.00.ino#L311

WiFi.mode(WIFI_AP_STA);  заменить на WiFi.mode(WIFI_STA);

**Comment by vvip-68** [comment]
Да, спасибо. Исправил.
