### ISSUE TITLE
При получении динамического адреса от роутера, остаётся статический

### ISSUE THREAD

**Issue by k0cm0c** [vvip-68/GyverLampWiFi#5]
https://github.com/vvip-68/GyverLampWiFi/blob/7b39d409c11533ff9d039b51cb9a21bcccb5e53c/firmware/GyverLampWiFi_v1.00/GyverLampWiFi_v1.00.ino#L200

byte IP_STA[] = {192, 168, 0, 116};  заменить на  byte IP_STA[] = {0, 0, 0, 0};

**Comment by vvip-68** [comment]
Это сделано специально для начального после прошивки получения указанного статического адреса. При первой загрузке. Далее этот адрес берется из EEPROM при каждом запуске прошивки. В приложении есть настройка - статический адрес. Если туда вбить 0.0.0.0 - он сохранится в EEPROM и при следующих загрузках будет получаться динамический адрес.

**Comment by k0cm0c** [comment]
Так и предполагал, но у всех разные подсети на роутерах, например - у меня 10.0.0.0/24, при первом включении после прошивки создается LampAP, настраивается сеть, пароль, а в поле статического адреса - "нет подключения"  далее, по логике обывателя - кнопка сохранить, и после перезагрузки подключается к роутеру, но с статическим IP 192.168.0.116 вместо какого либо из моей подсети. соответственно, к лампе не подключиться.
