### ISSUE TITLE
Две лампы

### ISSUE THREAD

**Issue by ermiyaev** [vvip-68/GyverLampWiFi#7]
Как насчёт возможности одновременного управления/синхронной работы двух и более ламп? (Не так, чтобы прям пиксель в пиксель совпадали, а режим и яркость)
Либо в приложение добавить возможность вносить более одного ip адреса ламп. Либо, возможно, ещё лучше дать второй лампе возможность брать информацию о состоянии и режиме работы с основной лампы

**Comment by vvip-68** [comment]
Ну это требует серьезной переработки кода... Не думаю, что у меня в ближайшем будущем найдется время но это, но чем черт не шутит, возможно когда-нибудь...
