### ISSUE TITLE
Длина пароля WiFi

### ISSUE THREAD

**Issue by inrovert** [vvip-68/GyverLampWiFi#8]
Доброго времени суток. Может быть я ошибаюсь, но мне показалось, что нашел несоответствие между длиной строковых переменных: строки 195, 196 в файле GyverLampWiFi_v1.00.ino и строки 112, 113 в файле eeprom.ino. Размеры перепутаны местами. Огромное спасибо за проделанную работу! Семья в восторге :-)

**Comment by inrovert** [comment]
Доброго времени суток. Может быть я ошибаюсь, но мне показалось, что нашел несоответствие между длиной строковых переменных: строки 195, 196 в файле GyverLampWiFi_v1.00.ino и строки 112, 113 в файле eeprom.ino. Размеры перепутаны местами. Огромное спасибо за проделанную работу! Семья в восторге :-)

**Comment by vvip-68** [comment]
Хм.. Ну, судя по описанию
  //  54-63   - имя точки доступа    - 10 байт
  //  64-79   - пароль точки доступа - 16 байт
именно в строках 112,113 указано правильно - такая длина и есть.
А вот в объявлении в основном файле строки 208,209
char apName[17] = "";                    // Имя сети в режиме точки доступа
char apPass[9]  = "";                    // Пароль подключения к точке доступа
таки получается да - перепутано, надо поменять местами.
Считаю имени точки доступа в 10 символов вполне достаточно. Это то как вы называете свою лампу, если у вас их несколько - "Lamp1", "Lamp2" например и все они работают в режиме точек доступа без подключения к сети
К  тому же в файле a_main.ino строки 397-407 где происходит получение этих параметров от приложения тоже прописано 10 на имя и 16 на пароль.
Исправил в исходниках
