### ISSUE TITLE
Power on TM1637

### ISSUE THREAD

**Issue by AndyIP70** [vvip-68/GyverLampWiFi#9]
Добрый день!
Лампа работает шикарно! Спасибо большое за прошивку!
Есть одно замечание. Может быть кому нибудь поможет.
Пришли из китая индикаторы TM1637. Брал тут:
https://ru.aliexpress.com/item/32845754229.html?spm=a2g0s.9042311.0.0.274233edIYNiAl
Ну так вот, на индикаторе написано, что он питается от 5 вольт.
Мой блок выдает 5.1 вольта. И индикатор уходит в защиту.
Оказалось, что индикатор хочет 3.3 вольта :) и замечательно работает!
И соответственно, запитывать его нужно непосредственно от выхода 3.3v на esp8266
Может быть стоит добавить это в FAQ в READ.ME?

**Comment by vvip-68** [comment]
Хм... На картинке индикатора написано вход питания 5V.
Ни разу не встречал TM1637, которые требовали бы 3.3 вольта. Все с чем сталкивался нормально работали от 5В. А вывод с выхода 3.3 В нормально тянет? Там ток допустимый, вроде, небольшой...

**Comment by AndyIP70** [comment]
Да. Тянет нормально.
